### ISSUE TITLE
Light nuclei in SMASH

### ISSUE THREAD

**Issue by gamejad** [smash-transport/smash#11]
Hi!
Exploring file "particles.txt.h" I've found the ability of SMASH to produce light nuclei (deuterons). It is very nice for my purposes, but I some questions about it.

Why deuterons productions "commented" by default? What does it means that "These are normally represented by neutrons and protons" and "should be uncommented only for SPECIFIC studies"? And how does SMASH separate deuteron and just close-located neutron and proton? Or more general - what is "deuteron" from the point of view of SMASH?

Thank you in advance for your reply.

**Comment by justinmohs** [comment]
Hi,

The deuterons were implemented by @doliinychenko for [this](https://inspirehep.net/literature/1693367) study where SMASH was used as an afterburner for high energy heavy ion collisions in a hybrid model.
At lower energies, the deuterons are represented by protons and neutrons, which should be bound to deuterons by the nuclear potentials (but we're also investigating how that approach works at sis18 energies).
When the deuterons are not commented out in the particles.txt, it means that the deuteron is a particle explicitly propagated in SMASH. Basically there are cross sections for some reactions to produce and destroy deuterons, for example nucleon+nucleon+pion <-> deuteron + pion with an intermediate step over a fake resonance called d'.
In order to use the deuterons, one needs to uncomment the lines for d and d' in particles.txt, the decay of the d' in the decaymodes.txt and, since the cross sections for deuterons are so large, set the cross section cutoff to 2000mb. Currently one has to do that in the code by hand. 
That would be in line 111 of constants.h.

**Comment by gamejad** [comment]
@justinmohs , so as I understood, to "turn on" deuterons I should change 3 header files:
1) ..../smash-master/src/include/smash/constants.h (line 111)
2)..../smash-master/input/decaymodes.txt (lines 856-857)
3).../smash-master/input/particles.txt (lines 164, 167)

is it right? And should I re-build SMASH after this, or changing of this lines is the only action I need to do?

**Comment by justinmohs** [comment]
Yes, those are he correct lines to change. After doing that you need to `cmake ..` and `make smash` again.
There is also an option tell smash which particles.txt and which decaymodes.txt files it should use when executing smash like this:
`./smash -d <path_to_decaymodes> -p <path_to_particles>`
So you could also have a copy of the decaymodes and particles file somewhere, modify it and use the copy. Just changing the particles and decaymodes doesn't require you to recompile but changing the cross section cutoff does.

**Comment by gamejad** [comment]
@justinmohs thanks a lot!

**Comment by doliinychenko** [comment]
Everything is correct, but there is one more detail. In the input folder we already have a input/light_nuclei/particles.txt and input/light_nuclei/decaymodes.txt files, which have d' and d lines properly uncommented.
