### ISSUE TITLE
output Npart and Ncoll

### ISSUE THREAD

**Issue by ayuz999** [smash-transport/smash#23]
Hi there, I wonder if it is possible to output "number of participant" and
 "number of binary collisions" in the final output?
Thanks
Yu

**Comment by justinmohs** [comment]
Hey,
We don't really want to explicitly give an Npart and an Ncoll directly in the smash output because it is not clear how to properly define these quantities in the way it is done in the Glauber model.
The number of participants could be defined as the number of particles that haven't participated in any scattering, but what happens in smash is that a binary collision triggers a bunch of secondary interactions within the target or projectile nucleus. These secondary collisions don't exist in the Glauber model and they also don't change the dynamics much, so you wouldn't want to count them.
Still it is not a good idea to just count the number of interactions between projectile and target nucleons because sometimes the secondary interactions are very important. 
Keeping in mind that this definition of Npart is not accurate, you can go through the extended particles output from smash and count the number of particles that satisfy `ncoll` = 0 to find something like an Npart. For Ncoll you can got through the collisions output and count the type of interactions you are interested in. @stdnmr can provide a code snipped to do that.
@elfnerhannah @nkblr

**Comment by stdnmr** [comment]
To get the number of binary collisions, a python script like this would do the job:

```python
sys.path.append("/.../smash-analysis/python_scripts")
import smash_basic_scripts as sbs

counter_binary_scatterings = 0
counter_binary_inelastic_scatterings = 0
with sbs.BinaryReader("collisions_binary.bin") as reader:
    for block in reader:
        if block["type"] == 'f':
            num_events = block["nevent"]
        if block["type"] == 'i':
            if (block["nin"] == 2 and block["nout"] == 2):
                counter_binary_scatterings +=1
                if (block["process_type"] != 1):  # ProcessType 1 for elastic scatterings in SMASH
                    counter_binary_inelastic_scatterings += 1

num_events += 1  # event counting starts at 0
print "number of binary collisions per event:", counter_binary_scatterings / float(num_events)
```

Note that this imports python script from the [`smash-analysis` repo](https://github.com/smash-transport/smash-analysis).

**Comment by ayuz999** [comment]
Thank you very much for your reply. It solves my issue.
I will now close this issue.
