### ISSUE TITLE
Smash_new_user

### ISSUE THREAD

**Issue by Mahmoud-moo** [smash-transport/smash#30]
Iam asking is there is any documentation file (User guide) for the functions that used to buildup code  to reproduce some of the figures in your site.
like the **Pythia** documentation

**Comment by akschaefer** [comment]
Hi Mahmoud-moo,
thank you for opening the issue.
Unfortunately, I am not certain to which figures you are referring. Do you mean those listed in the publications section of [https://smash-transport.github.io](https://smash-transport.github.io)? Or the ones produced for SMASH-2.0.1, which are available here: [http://theory.gsi.de/~smash/analysis_suite/SMASH-2.0.1/index.html](http://theory.gsi.de/~smash/analysis_suite/SMASH-2.0.1/index.html)? The latter were generated by means of the smash-analysis, which is also available on GitHub: [https://github.com/smash-transport/smash-analysis](https://github.com/smash-transport/smash-analysis).

Let me know if you need further information.

**Comment by gabriele-inghirami** [comment]
Hi Mahmoud-moo!

We take the chance to inform you that a new SMASH version is available (2.1):
https://github.com/smash-transport/smash/releases/tag/SMASH-2.1
and that on http://theory.gsi.de/~smash/analysis_suite/SMASH-2.1/index.html
you can see the plots of the results with the new version in some real cases.

As my (more expert) senior colleague Anna (@akschaefer ) already pointed out, in the smash-analysis suite, which has been recently updated tot support python3 (https://github.com/smash-transport/smash-analysis) you can find almost all (apart from some experimental data) what you need to reproduce the figures shown in the web.
More precisely, in the _test_ directory you can find several subdirectories, one for each physics case presented in the website, and in each of them the _config.yaml_ file to configure the SMASH runs and the python scripts to analyze the results and produce the plots (which use some common python utilities in the _python_scripts_ directory). 
Unfortunately, there are not detailed step by step explanations about what the scripts do, as their aim is to reproduce experimental results to ensure the quality of the code, so they are a bit complicated and not appropriate for pedagogical purposes.

Regarding the publications, for all the "recent" ones on arxiv.org you can find associated "ancillary" files with, at least, the raw data of the plots and sometimes also the plotting scripts and the SMASH configuration files.

As far as I know, there are not official SMASH tutorials, however, on : https://indico.cern.ch/event/1055111/timetable/, in the context of the JETSCAPE Online Summer School 2021, you can find some lectures about SMASH given by a former group member and SMASH developer,  Dmytro Oliinychenko, which include also a practical hands on session. It is possible to download the slides and watch the videos of the lectures.

Is the issue solved?
If this is the case, please, close it, otherwise, please, ask more into detail what you would like to know.

Thank you.

Best regards,
Gabriele
