### ISSUE TITLE
SMASH installation on Macbook with M1 chip

### ISSUE THREAD

**Issue by vsandul** [smash-transport/smash#31]
Dear SMASH developers!
I am on transfer from Linux to MacOS with M1 chip and I've faced with the problem: the familiar installation instruction seems to be inoperative on new Apple laptops. Didn't you or anyone else tried to install SMASH on Mac M1 laptop and in case of success can you give an instructions?

**Comment by vsandul** [comment]
@stdnmr usage of Rosetta terminal really helps and I succeeded to install SMASH, but since my ROOT has compiled with M1 chip, for SMASH building I was compelled to turn off the SMASH compatibility with ROOT (-DUSE_ROOT=OFF). Hence my question is transforming to the next: how can I build SMASH linked with some special ROOT version?

**Comment by stdnmr** [comment]
@vsandul we coincidentally got our hands on an M1 mac machine and are currently testing the compilation. 

From our experience it is better to not use the precompile binaries of ROOT.

To find a specific version of ROOT you need to "tell" the find_package from cmake where to look. You can find the order of the command looks [here](https://cmake.org/cmake/help/latest/command/find_package.html). My ideas would be to try invoking cmake  as follows either `cmake .. -DCMAKE_PREFIX_PATH=<path-to-special-root>`or better if you run a newer version of cmake (version 3.12 or newer) `cmake .. -DROOT_ROOT =<path-to-special-root>`. Hope this helps.

**Comment by AxelKrypton** [comment]
@vsandul I recently took care of made all needed adjustments to SMASH in order to fully support Apple Silicon chips. The upcoming new version of SMASH will allow you to work on your M1 Apple machine, without any need of the Rosetta mode. 🥳 You are clearly still free to use Rosetta `x86_64` emulator, if you wish. However, **you should not mix the two approaches** and e.g. try to use ROOT compiled for a M1 ARM processor from a Rosetta terminal trying to build SMASH. This is very likely (if not certainly) going to fail.

In general, it is a while that `brew` supports new M1 Apple chips and most prerequisites for SMASH can be installed using brew formulae. I would actually suggest doing so.

As additional information, there is a [brew formula for ROOT](https://formulae.brew.sh/formula/root), which can be used on M1 machines with BigSur macOS, but unfortunately not (yet) with Monterey. On Monterey you now need to build ROOT yourself from source, following the [official documentation](https://root.cern/install/build_from_source/). As @stdnmr suggested you, pre-compiled binaries are not always working smoothly with SMASH and you might want to built anyhow ROOT from source.

In their quick start guide, they assume you want to build ROOT in its full glory and, hence, suggest to use
```console
cmake -DCMAKE_INSTALL_PREFIX=<installdir> <sourcedir>
```
that will prepare a full build. There is the possibility to make a much smaller built, i.e. via
```console
cmake -DCMAKE_CXX_STANDARD=14 -Dminimal=ON -DCMAKE_INSTALL_PREFIX=<installdir> <sourcedir>
```
where `-Dminimal=ON` enables the minimal mode and `-DCMAKE_CXX_STANDARD=14` is needed for recent versions, as also explained in the README file of SMASH. You might need to install [some dependencies](https://root.cern/install/dependencies), but this is usually taken care by `xcode-select --install`, which I guess you already did on your machine. Beyond that I preferred to `brew install nlohmann-json`, since ROOT `cmake` was warning me about not finding it. This is not required though, since there is a `builtin_nlohmannjson` ROOT build option.

Once ROOT is built, please refer to the [previous note](https://github.com/smash-transport/smash/issues/31#issuecomment-967072371) to make sure CMake finds it.

**Comment by akschaefer** [comment]
There is a new SMASH release, feel free to try it on your M1 Macbook: https://github.com/smash-transport/smash/releases/tag/SMASH-2.1

**Comment by vsandul** [comment]
@akschaefer I confirm that new SMASH 2.1 builds and works on M1 chips properly. Thanks a lot!

**Comment by akschaefer** [comment]
Glad to hear it works, thanks for the feedback!
