### ISSUE TITLE
Cannot compile SMASH due to issue with Pythia ver. 8.303

### ISSUE THREAD

**Issue by FlowNICA** [smash-transport/smash#38]
Greetings all, 
I have a problem compiling SMASH ver. 2.1.1 (namely `smash/src/stringprocess.cc` causes errors) because of the missing member of Pythia classes:

```
smash/src/stringprocess.cc:69:20: error: ‘class Pythia8::SigmaTotal’ has no member named ‘initInfoPtr’
/src/stringprocess.cc:71:25: error: no matching function for call to ‘Pythia8::SigmaTotal::init()’
/src/stringprocess.cc:597:60: error: no matching function for call to ‘Pythia8::Pythia::next(double&)’
```

I'm sure I'm using the correct version of Pythia8 (ver. 8.303).
I'm using gcc ver. 4.8.5, GSL ver. 2.5, eigen ver. 3.4.0, boost ver. 1.68.0, and root ver. 6.16.

I've tried SMASH ver. 2.1.2 - the issue remains.

**Comment by gabriele-inghirami** [comment]
Hi!
In addition to 8.303, do you have also other versions of Pythia installed?
What is the output of: `printenv | grep PYTHIA`?

**Comment by FlowNICA** [comment]
Hello,

There're no additional versions of Pythia8 - `printenv | grep PYTHIA` shows nothing.
Cmake finds the required custom Pythia fine. I used `-DPythia_CONFIG_EXECUTABLE` and `-DPythia_LIBRARY` options:


```
-- Looking for Pythia... - using pythia8-config executable
-- ** Pythia version ok: 8.303, required 8.303.
-- Found Pythia: <path>/pythia8303/lib/libpythia8.so (Required is exact version "8.303")
-- ** Pythia 8 library: <path>/pythia8303/lib/libpythia8.so
-- ** Pythia 8 include: <path>/pythia8303/include
-- ** Pythia 8 xmldoc:  <path>/pythia8303/share/Pythia8/xmldoc
```

**Comment by gabriele-inghirami** [comment]
Can you, please, write explicitly how you invoked `cmake`?
`Pythia_LIBRARY` should be set by ` -DPythia_CONFIG_EXECUTABLE` and, unless you manually edited the output before posting, cmake should get write to the stdout something like:
```
 -- Looking for Pythia... - using pythia8-config executable
-- ** Pythia version ok: 8.303, required 8.303.
-- Found Pythia: /home/runner/work/smash/smash/pythia8303/lib/libpythia8.so (Required is exact version "8.303") 
-- ** Pythia 8 library: /home/runner/work/smash/smash/pythia8303/lib/libpythia8.so
-- ** Pythia 8 include: /home/runner/work/smash/smash/pythia8303/include
-- ** Pythia 8 xmldoc:  /home/runner/work/smash/smash/pythia8303/share/Pythia8/xmldoc
```
i.e. the full path, not just "<path>/...".
Can you, please, try again in a clean build directory without the `-DPythia_LIBRARY` option, which should be redundant?

**Comment by gabriele-inghirami** [comment]
Hi!
I tried to reproduce a similar problem with old versions of Fedora GNU/Linux and Pythia, but without success.
However, I've found a june19p2 fairsoft cvmfs distribution in the cluster at GSI, which should be rather close to the version of Pythia installed in your system, and I've seen that it comes with Pythia 8.240, so for further testing next time (shortly) I will use that.
Meanwhile, could you please try again, in a clean build directory, with:
`export LD_LIBRARY_PATH=/lustre/stor1/parfenov/Soft/pythia8303/lib:$LD_LIBRARY_PATH;`
followed by your cmake command?

**Comment by gabriele-inghirami** [comment]
Hi!
Hopefully, as a temporary solution, you should be able to compile SMASH after replacing the file (or editing it as explained later):
_smash/src/CMakeLists.txt_
with the attached one, using your full cmake command (with the` -DPythia_LIBRARY` option, to avoid it one would need to modify also _smash/cmake/FindPythia.cmake_, a step that I preferred to avoid for the moment).
I tested this workaround with the _fairsoft/jun19p2_ software distribution for CentOS7 in the cluster at GSI and it worked (compilation and testsuite); it's not exactly your environment, but it should be pretty close to it (gcc 4.8.5, root 6.16.0,  boost  1.68.0), so I am moderately optimistic that it will work also for you.

The problem is that the current cmake configuration script does not correctly replace a Pythia library already installed at a system level. The option `-DPythia_LIBRARY` fixes the problem for the shared library itself, but not for the include files, because the system path for the header files found for ROOT is good also for Pythia and it used before that determined by `pythia8-config`.
The fix consists in prepending the path of the directory of the header files found by `pythia8-config` instead of appending it.
```
$ git diff
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index 1909ba3..0cacfcd 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -115,7 +115,7 @@ endif()
 # find Pythia
 find_package(Pythia 8.303 EXACT REQUIRED)
 if(Pythia_FOUND)
-  include_directories(SYSTEM
+  include_directories(BEFORE SYSTEM
      "${Pythia_INCLUDE_DIRS}"
      )
   link_directories("${Pythia_LIBDIR}")
```
[CMakeLists.txt](https://github.com/smash-transport/smash/files/8028629/CMakeLists.txt)

Please, let me know if this modification solves the compilation problem also for you.
Thank you for your patience and for your collaboration!

**Comment by FlowNICA** [comment]
Hello,
Sorry for such a delayed reply. Your suggestion with src/CMakeLists.txt modification works!
Thank you for the help.
