### ISSUE TITLE
A couple of unit tests fail

### ISSUE THREAD

**Issue by Silence2107** [smash-transport/smash#44]
Dear sir/madam,
My name is Pavlo Panasiuk, I am busy with comparing several MC generators. Recently we discussed an issue related to SMASH-1.8 installation (thanks for helping with that). Now that I ran unit tests on both SMASH-2.2, SMASH-1.8, I have encountered a few fails, namely
1) 2.2 : 29 - integrate failed
2) 1.8 : 29 - integrate , 48 - photons failed

It does not seem like much, but I want to be sure these are either unimportant or fixable. To be precise, I am going to run the models in two ways:
1) Au+Au collider on low energies, with default interaction constants etc
2) Infinite matter simulation on about same densities, with default interaction constants etc.

Please let me know if these are known issues (and whether they are severe) and whether I can/need to do something about them.
If you need any test outputs, please let me know how do I extract them.

Thanks in advance.

**Comment by AxelKrypton** [comment]
Thanks for reporting this. All tests are supposed to pass and any failure is worth to be looked into. However, since having all tests passing is a necessary condition for us to put out a new release, this means that in all our testing environments the tests were passing both with `SMASH-1.8` and `SMASH-2.2`. I just quickly checked on my two machines and I could not reproduce your failures, hence I suspect that it might be something related to the different environments. We will now try to check in the other environments we have at hand and let you know.

In the meanwhile, it would be helpful to see the reason of the failure. In your build folders, once the `make` command is successfully finished, you will see an `integrate` and a `photons` executables. Running these is what `ctest` does underneath and you can always manually run them from the build folder as `./integrate` or `./photons` in order to see their output. Just for your information, `ctest` can also give you more output, but it does not by default, and you need to run it as `ctest --output-on-failure`. To enable this behaviour for all `ctest` commands, you can set [the `CTEST_OUTPUT_ON_FAILURE` environment variable](https://cmake.org/cmake/help/latest/manual/ctest.1.html#cmdoption-ctest-output-on-failure).

Can you please run those executable and report here the output you get? It would be also useful to know which output you get from `./smash --version`.

**Comment by Silence2107** [comment]
These are outputs, commands I used are inside as well.

Let me know what you think.

[smash2.2.log](https://github.com/smash-transport/smash/files/10083430/smash2.2.log)
[smash1.8.log](https://github.com/smash-transport/smash/files/10083431/smash1.8.log)

**Comment by gabriele-inghirami** [comment]
> Let me know what you think.

So far we have not been able to reproduce the failures, but we'll continue to examine the problem.
This message is just to inform you that we are not neglecting the issue, but that the investigations might take some time.

**Comment by AxelKrypton** [comment]
Let me add that, since we could not reproduce your failures so far, it would be helpful to have more information. In particular, if you could tell us which `cmake` command you used and its output, we might try to get as close as possible to your environment.

**Comment by Silence2107** [comment]
@AxelKrypton 
I rebuilt both versions from the scratch to generate cmake outputs, but ctest fails at the same spots.
Following commands were ran:

cmake -DCMAKE_INSTALL_PREFIX=../smashX.Y_installdir -DPythia_CONFIG_EXECUTABLE=../../pythia8ABC/bin/pythia8-config -DCMAKE_CXX_STANDARD=14 ../smashX.Y_src
make -j$(nproc)
ctest --output-on_failure -j$(nproc)

[smash2.2_build.log](https://github.com/smash-transport/smash/files/10088166/smash2.2_build.log)
[smash1.8_build.log](https://github.com/smash-transport/smash/files/10088167/smash1.8_build.log)

**Comment by AxelKrypton** [comment]
@Silence2107 thanks for providing the more detailed information.

I now tried to be as close as possible to your environment. In particular,
```console
$ ./smash --version
SMASH-1.8
Branch   : HEAD
System   : Linux-3.10.0-1160.31.1.el7.x86_64
Compiler : GNU 9.3.0
Build    : RelWithDebInfo
Date     : 2022-11-25T18:12:56
```
and using your same versions of the compiler as well as GSL and Eigen3 (and Pythia, of course). Only Boost differed (I used version 1.71) but this is used for handling files, so no calculation. **No failure could be reproduced**. Speaking with colleagues we suspect that something might not be properly working with your GSL library. It is probably worth to try to locally install e.g. version 2.5 which can be done along the lines
```bash
wget https://mirrors.kernel.org/gnu/gsl/gsl-2.5.tar.gz
tar xf gsl-2.5.tar.gz
mv gsl-2.5 gsl-2.5-src
mkdir gsl-2.5
cd gsl-2.5-src/
./configure --prefix=/global/path/to/gsl-2.5   # <- put here the correct path
make -j$(nproc)
make install
```
and then let CMake find it using the environment variable `GSL_ROOT_DIR`, i.e. in SMASH build folder issuing
```
GSL_ROOT_DIR=/global/path/to/gsl-2.5 cmake [...]
```
or exporting the variable via `export GSL_ROOT_DIR=/global/path/to/gsl-2.5`. In CMake output you will get confirmed that the local installation was found.

The reason why our guess points to GSL is that this library is used in both failing tests. Of course this is only a blind guess, since it is basically impossible for us to debug a not-reproducible failure. There might be many other explanations, of course. Maybe you could also try to reproduce the failure yourself on a different machine, like a laptop or a desktop machine (you do not need to install ROOT for that).

If you do any of the two suggested attempts (new GSL or different machine), we would be happy to get an update from your side.

---

Not being able to reproduce the failure, we would be inclined to think that there is something not properly working on your side. Leaving this aside for a moment, just a couple of statements to be taken with a pinch of salt, as we could not reproduce your failures.
* Photons treatment needs to be intentionally enabled in the input file, as explained in [the corresponding section of the user guide](http://theory.gsi.de/~smash//userguide/2.2/input_photons.html). Said differently, SMASH does not include them.
* The failure in the `integrate` test is a 1 ulp difference and it might be that we required a too strict precision in that particular test and I would not be too worried about that. I will not investigate further this aspect for the moment.

**Comment by Silence2107** [comment]
@AxelKrypton thanks for the explanation.

Given your explanation I understand, that I do not care much about these tests, but I decided to try it out anyway. Indeed, new gsl build resolved all the fails for me. Nice catch!

Thanks a lot for consideration.
