### ISSUE TITLE
SMASH runs slowly on a new system

### ISSUE THREAD

**Issue by YoshiniBailung** [smash-transport/smash#53]
Dear experts

I have been running SMASH on a Ubuntu 18 system with an 9th generation intel i7 chip. The performance of SMASH on this machine is reasonably good (1000 events in ~3 hours for central Au+Au collisions at 39 GeV). Recently I moved to a newer PC with a 12th gen intel i9 chipset running Ubuntu 22. The speed of SMASH has gone down drastically, I was able to reach close to a hundred events in 3 hours for the same collision system. This is compared on the single core performance of both systems. I even checked if the new chipset was running on lower clock-speeds but that does not seem to be the case (3800 MHz vs 4900 MHz). Is this a limitation of the new generation processors which use a mix of performance + efficiency cores, or am I overlooking any missing detail?

Thanks a lot in advance

**Comment by gabriele-inghirami** [comment]
Hi!

I am not an expert of cpus, but 100 events instead of 1000 events in the same time is a significant reduction of performance...

I have a few questions:

- Did you notice a similar loss of performance also with other numerical software or only with SMASH?

- Have you tried to always use the top (without overclocking) cpu frequency by setting the cpu frequency governor (https://www.kernel.org/doc/Documentation/cpu-freq/governors.txt) on "performance"? (see, e.g. https://fasterdata.es.net/host-tuning/linux/100g-tuning/cpu-governor/)

- Did you use the same SMASH version on both systems? Which one? (`./smash --version`)

- Did you use the native gcc compiler in both cases? Which versions? Perhaps 7.4.0 and 11.3.0? With which flags?

- Apart from the cpu, do the two system have relevant different features? For example, do they both use local hard drives? Does the new system have enough RAM to avoid swapping? (Sorry for this trivial questions, it's just to rule out some of the simplest explanations)

**Comment by YoshiniBailung** [comment]
Thank you for all the pointers and checks. The check on SMASH version and the gcc compiler solved my issue. Indeed, the gcc compilers were 7.5.0 and 11.3.0 in ubuntu 18 and 22 respectively. Both SMASH versions are 2.2.1. I tried downgrading the gcc compiler but faced issues while building; so I downloaded the newest SMASH (3.0) and did a fresh build on gcc 11.3.0. Now the performance is fine and as good as my other system. I also set all the cpus to performance, although that does not seem to have a massive impact on the overall performance. Although, I do see a difference in the clock speeds of the cores when I move from a single to multiple cores in both systems. On the older system `cat /proc/cpuinfo | grep "MHz"` yields all 8 cores to `cpu MHz: 3599.999' which is the highest freq of the chip (same on a single core). On the new system I ran over 20 cores and the clock speeds are around `cpu MHz: 2500.000`; on the contrary it is close to `5000 MHz` on single core (running over 8 cores gives about 3200 MHz). However this should be "by design" for the new generation chips and nothing specific for SMASH. Thanks a lot again!
